[project]
name = "marimo-challenge-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "einops>=0.8.2",
    "google-genai>=2.10.0",
    "huggingface-hub>=1.21.0",
    "ipykernel>=7.3.0",
    "marimo>=0.23.10",
    "matplotlib>=3.11.0",
    "plotly>=6.8.0",
    "pydantic-ai-slim>=2.0.0",
    "scikit-learn>=1.9.0",
    "tqdm>=4.67.1",
    "torchvision>=0.27.1",
    "umap-learn>=0.5.12",
    "ipywidgets>=8.1.8",
    "jax[cuda13]>=0.10.2",
    "equinox>=0.13.8",
    "optax>=0.2.8",
    "scikit-image>=0.26.0",
]
license = {file = "LICENSE"}
authors = [
    {name = "Mathis Boultoureau", email = "contact@mboultoureau.com"},
    {name = "vctr-dng", email = "94930828+vctr-dng@users.noreply.github.com"}
]

[dependency-groups]
dev = [
    "pyrefly>=1.1.1",
]
